# Generated by Django 5.1.4 on 2025-01-05 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arquivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_arquivo', models.CharField(max_length=255)),
                ('arquivo', models.BinaryField()),
                ('id_cliente', models.CharField(default='', max_length=20)),
                ('dateCreate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_referencia', models.CharField(max_length=255, unique=True)),
                ('status_compra', models.CharField(default='Pendente', max_length=100)),
                ('dados_requisicao', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clienteId', models.CharField(default='', max_length=50, null=True)),
                ('TokenLove', models.CharField(default='', max_length=150)),
                ('qrcode', models.BinaryField(blank=True, default=None, null=True)),
                ('SendEmailCliente', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_type', models.CharField(max_length=100)),
                ('details', models.TextField()),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='florArq',
            fields=[
                ('flor', models.BinaryField()),
                ('idflor', models.IntegerField(default=1, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='iconLogoPage',
            fields=[
                ('icon', models.BinaryField()),
                ('logo', models.BinaryField()),
                ('idLogoicon', models.IntegerField(default=0, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='PageNotCarregadaErro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_referencia', models.CharField(max_length=255, unique=True)),
                ('error_type', models.CharField(max_length=100)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentAprovedCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_id', models.CharField(max_length=50)),
                ('collection_status', models.CharField(max_length=50)),
                ('payment_id', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('external_reference', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_type', models.CharField(max_length=50)),
                ('merchant_order_id', models.CharField(max_length=50)),
                ('preference_id', models.CharField(max_length=100)),
                ('site_id', models.CharField(max_length=50)),
                ('processing_mode', models.CharField(max_length=50)),
                ('merchant_account_id', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='paymentNotProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_referencia', models.CharField(max_length=255, unique=True)),
                ('status_compra', models.CharField(default='Pendente', max_length=100)),
                ('clienteId', models.CharField(default='', max_length=50, null=True)),
                ('details', models.TextField()),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Qrcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_referencia', models.CharField(max_length=255, unique=True)),
                ('qrcode', models.BinaryField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='QrcodeBinary',
            fields=[
                ('qrcode', models.BinaryField()),
                ('idqrcode', models.IntegerField(default=1, primary_key=True, serialize=False)),
            ],
        ),
    ]
