# Generated by Django 5.0.3 on 2024-11-03 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_referencia', models.CharField(max_length=255, unique=True)),
                ('status_compra', models.CharField(default='Pendente', max_length=100)),
                ('dados_requisicao', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_type', models.CharField(max_length=100)),
                ('details', models.TextField()),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentAprovedCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_id', models.CharField(max_length=50)),
                ('collection_status', models.CharField(max_length=50)),
                ('payment_id', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('external_reference', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_type', models.CharField(max_length=50)),
                ('merchant_order_id', models.CharField(max_length=50)),
                ('preference_id', models.CharField(max_length=100)),
                ('site_id', models.CharField(max_length=50)),
                ('processing_mode', models.CharField(max_length=50)),
                ('merchant_account_id', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
