# Generated by Django 5.1.4 on 2025-01-05 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ModelSite', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qrcodebinary',
            old_name='qrcode',
            new_name='qrcodemodel',
        ),
    ]
