# Generated by Django 5.1.4 on 2025-01-05 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModelSite', '0002_rename_qrcode_qrcodebinary_qrcodemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcodebinary',
            name='idqrcode',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
