# Generated by Django 5.0.3 on 2024-11-09 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModelSite', '0003_compra_clienteid_alter_arquivo_id_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='linkLove',
            field=models.CharField(default='', max_length=255),
        ),
    ]
