# Generated by Django 5.0.3 on 2024-11-09 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModelSite', '0004_compra_linklove'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='qrcode',
            field=models.BinaryField(default=None),
        ),
    ]
