# Generated by Django 5.0.3 on 2024-11-09 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModelSite', '0005_compra_qrcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='qrcode',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
