# Generated by Django 5.0.3 on 2024-11-09 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModelSite', '0006_alter_compra_qrcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='clienteId',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
