# Generated by Django 5.0.3 on 2024-11-10 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModelSite', '0007_alter_compra_clienteid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='qrcode',
            field=models.BinaryField(blank=True, default=None, null=True),
        ),
    ]
