# Generated by Django 5.0.3 on 2024-11-12 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModelSite', '0008_alter_compra_qrcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='paymentNotProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_referencia', models.CharField(max_length=255, unique=True)),
                ('status_compra', models.CharField(default='Pendente', max_length=100)),
                ('clienteId', models.CharField(default='', max_length=50, null=True)),
                ('details', models.TextField()),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
