# Generated by Django 5.0.3 on 2024-11-16 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModelSite', '0010_delete_arquivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arquivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_arquivo', models.CharField(max_length=255)),
                ('arquivo', models.BinaryField()),
                ('id_cliente', models.IntegerField(default=0)),
                ('dateCreate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
