# Generated by Django 4.2.7 on 2024-11-25 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ModelSite', '0013_pagenotcarregadaerro'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Compra',
        ),
    ]
