# Generated by Django 4.2.7 on 2024-11-25 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModelSite', '0014_delete_compra'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_referencia', models.CharField(max_length=255, unique=True)),
                ('status_compra', models.CharField(default='Pendente', max_length=100)),
                ('dados_requisicao', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clienteId', models.CharField(default='', max_length=50, null=True)),
                ('TokenLove', models.CharField(default='', max_length=150)),
                ('qrcode', models.BinaryField(blank=True, default=None, null=True)),
            ],
        ),
    ]
